Remove iphonesimulator6.1 from target SDKs
Because tests fails from following error message

```
BTKInjectorDuckTypingTests.m:34:90: error: reference to 'NSNotFound' is ambiguous
        XCTAssertTrue(([exception.reason rangeOfString:@"does not conforms"].location != NSNotFound)
```